name: Executar Testes com Jest e Cobertura

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm cache clean --force

      - run: npm install

      - run: ls -l ./node_modules/.bin/jest

      - run: chmod +x ./node_modules/.bin/jest

      - name: Rodar testes com cobertura
        run: ./node_modules/.bin/jest --coverage

      - name: Fazer upload do relatório de cobertura
        uses: actions/upload-artifact@v2
        with:
          name: cobertura-jest
          path: coverage/
